version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "10000:5432"
    environment:
      POSTGRES_USER: ezchess
      POSTGRES_PASSWORD: 123
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  
volumes:
  local_pgdata:
